# Generated by Django 3.1.3 on 2020-12-20 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201220_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date Time Field')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lawyer', to=settings.AUTH_USER_MODEL, verbose_name='Lawyer')),
            ],
        ),
    ]
