# Generated by Django 3.1.3 on 2021-01-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Paid Amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad'), ('DBBL', 'DBBL'), ('Skrill', 'Skrill'), ('Aqua', 'Aqua')], default='bKash', max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trxnid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
